name: Pets
main: taqdees\Pets\Main
version: 1.0.0
api: 5.0.0
author: Taqdees
description: Spawn pet mobs that follow you

permissions:
  pets.command:
    description: Allows using the /pets command
    default: true
  pets.type.zombie:
    description: Allows spawning zombie pet
    default: op
  pets.type.skeleton:
    description: Allows spawning skeleton pet
    default: op
  pets.type.creeper:
    description: Allows spawning creeper pet
    default: op
  pets.type.spider:
    description: Allows spawning spider pet
    default: op
  pets.type.cow:
    description: Allows spawning cow pet
    default: op
  pets.type.pig:
    description: Allows spawning pig pet
    default: op
  pets.type.sheep:
    description: Allows spawning sheep pet
    default: op
  pets.type.chicken:
    description: Allows spawning chicken pet
    default: op
  pets.type.blaze:
    description: Allows spawning blaze pet
    default: op
  pets.type.enderman:
    description: Allows spawning enderman pet
    default: op
  pets.type.wolf:
    description: Allows spawning wolf pet
    default: op
  pets.type.ghast:
    description: Allows spawning ghast pet
    default: op
  pets.type.slime:
    description: Allows spawning slime pet
    default: op
  pets.type.magma_cube:
    description: Allows spawning magma cube pet
    default: op
  pets.type.witch:
    description: Allows spawning witch pet
    default: op
  pets.type.villager:
    description: Allows spawning villager pet
    default: op
  pets.type.squid:
    description: Allows spawning squid pet
    default: op